### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by jacobsvante** [houseabsolute/pg-pretty#4]
I just read your related blog posts and found this project to be really interesting. I like the thought of a compiled replacement to pgFormatter, for usage in your editor / pre-commit framework / CI infrastructure.

So I'm just curious what your thoughts are on the project? Any plans on continuing its development?

**Comment by autarch** [comment]
The project is kind of stalled right now. The big issue is that I was never able to come up with a coherent approach to handling the to-be-formatted output. There's some WIP in the `new-formatter` branch but I don't think the approach in that branch is quite right either.

**Comment by jacobsvante** [comment]
Gotcha. Judging by your blog posts I can see that it's a big undertaking. Good luck to you if you (hopefully) resume the work one day!

**Comment by autarch** [comment]
I'm going to close this since it's not really a bug report.
